"""new pets

Revision ID: 191e07adf868
Revises: cf0b0962b043
Create Date: 2023-03-08 11:08:12.961309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191e07adf868'
down_revision = 'cf0b0962b043'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
