"""association_proxy

Revision ID: 1dff498d7817
Revises: ec270917635a
Create Date: 2023-03-08 09:42:18.599227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dff498d7817'
down_revision = 'ec270917635a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
