"""new pets

Revision ID: 221f0ffa639f
Revises: 74634487a97e
Create Date: 2023-03-08 10:43:33.145397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221f0ffa639f'
down_revision = '74634487a97e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
