"""merged heads

Revision ID: 22e45bdca35e
Revises: 23d19df891e2
Create Date: 2023-03-08 12:16:23.316098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e45bdca35e'
down_revision = '23d19df891e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
