"""new pets

Revision ID: 251335cc39c2
Revises: c4ab3814cd7b
Create Date: 2023-03-08 10:28:42.171035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251335cc39c2'
down_revision = 'c4ab3814cd7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
