"""new pets

Revision ID: 43ec13881d46
Revises: 221f0ffa639f
Create Date: 2023-03-08 10:44:29.904190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ec13881d46'
down_revision = '221f0ffa639f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
