"""added orders

Revision ID: 5e51bec4a69d
Revises: dcbd1d92d653
Create Date: 2023-03-07 15:40:16.504670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e51bec4a69d'
down_revision = 'dcbd1d92d653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_item_id', sa.Integer(), nullable=True),
    sa.Column('shopping_cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_item_id'], ['pet_items.id'], ),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pet_items', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('pet_items', sa.Column('shopping_cart_id', sa.Integer(), nullable=True))
    op.drop_index('ix_pet_items_name', table_name='pet_items')
    op.create_foreign_key(None, 'pet_items', 'shopping_carts', ['shopping_cart_id'], ['id'])
    op.create_foreign_key(None, 'pet_items', 'stores', ['store_id'], ['id'])
    op.drop_column('pet_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_items', sa.Column('price', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'pet_items', type_='foreignkey')
    op.drop_constraint(None, 'pet_items', type_='foreignkey')
    op.create_index('ix_pet_items_name', 'pet_items', ['name'], unique=False)
    op.drop_column('pet_items', 'shopping_cart_id')
    op.drop_column('pet_items', 'store_id')
    op.drop_table('orders')
    op.drop_table('shopping_carts')
    # ### end Alembic commands ###
