"""new pets

Revision ID: 74634487a97e
Revises: afe1970315ef
Create Date: 2023-03-08 10:42:47.056270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74634487a97e'
down_revision = 'afe1970315ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
