"""new pets

Revision ID: bf07923b7c0c
Revises: 1dff498d7817
Create Date: 2023-03-08 10:23:18.960321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf07923b7c0c'
down_revision = '1dff498d7817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
