"""new pets

Revision ID: c4ab3814cd7b
Revises: bf07923b7c0c
Create Date: 2023-03-08 10:27:42.944860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ab3814cd7b'
down_revision = 'bf07923b7c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
