"""new pets

Revision ID: eb8e07ff7be6
Revises: 22e45bdca35e
Create Date: 2023-03-08 13:54:54.658902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8e07ff7be6'
down_revision = '22e45bdca35e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
